#the docker-compose.yml file for react app and node app
version: '3.7'
services:
  myapp:
    build: ./myapp
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./myapp/src:/usr/src/app/src
    depends_on:
      - back
    networks:
      - guess
  back:
    build: ./server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - guess

networks:
  guess:

volumes:
  node_modules: